path_to_csv: "pkg/importer/testdata/data_dump_valid.csv"
storage_option: "scylla"
http:
  addr: "localhost:8080"
resolver:
  write_timeout: "1s"
  read_timeout: "1s"
  importer:
    separator: ","
    verbose: true
scylla:
  servers: ["127.0.0.1:9042"]
  keyspace: "geoloc"
  timeout: "950ms"
  connect_timeout: "1s"
  num_conns: 10
  writer_pool_size: 10
  write_queue_size: 10000
  reader_pool_size: 1
  read_queue_size: 100
